CREATE TABLE `events` (
    `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
    `title` VARCHAR(255) NOT NULL,
    `slug` VARCHAR(255) NOT NULL UNIQUE,
    `content` LONGTEXT NOT NULL,
    `event_date` DATE NOT NULL,
    `event_time` TIME NOT NULL,
    `location` VARCHAR(255) NOT NULL,
    `event_type` ENUM('free', 'paid') NOT NULL DEFAULT 'free',
    `cover_image` VARCHAR(500) DEFAULT NULL,
    `status` ENUM('pending', 'launched', 'cancelled') NOT NULL DEFAULT 'pending',
    `author_id` BIGINT UNSIGNED NOT NULL,
    `seo_title` VARCHAR(60) NULL,
    `seo_description` VARCHAR(160) NULL,
    `seo_keywords` VARCHAR(255) NULL,
    `published_at` TIMESTAMP NULL,
    `created_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    `updated_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    FOREIGN KEY (author_id) REFERENCES users(id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;