CREATE TABLE `resources` (
    `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
    `title` VARCHAR(255) NOT NULL,
    `description` TEXT NOT NULL,
    `file_name` VARCHAR(255) NOT NULL,
    `file_path` VARCHAR(500) NOT NULL,
    `file_size` BIGINT UNSIGNED NOT NULL,
    `file_type` ENUM('image', 'document', 'video', 'audio', 'other') NOT NULL DEFAULT 'other',
    `file_extension` VARCHAR(10) NOT NULL,
    `mime_type` VARCHAR(100) NOT NULL,
    `price` DECIMAL(10, 2) DEFAULT 0.00,
    `is_free` BOOLEAN DEFAULT TRUE,
    `status` ENUM('published', 'draft', 'pending') NOT NULL DEFAULT 'draft',
    `download_count` INT UNSIGNED DEFAULT 0,
    `paid_download_count` INT UNSIGNED DEFAULT 0,
    `revenue_generated` DECIMAL(12, 2) DEFAULT 0.00,
    `featured_image` VARCHAR(500) NOT NULL,
    `created_by` BIGINT UNSIGNED NOT NULL,
    `published_at` TIMESTAMP NULL,
    `created_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    `updated_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    
    INDEX `idx_status` (`status`),
    INDEX `idx_file_type` (`file_type`),
    INDEX `idx_price` (`price`),
    INDEX `idx_created_at` (`created_at`),
    INDEX `idx_download_count` (`download_count`),
    FOREIGN KEY (`created_by`) REFERENCES users(`id`) ON DELETE CASCADE
);